"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.router = void 0;
const express_1 = require("express");
const CreateEncryptController_1 = require("./controllers/CreateEncryptController");
const CreateDecryptController_1 = require("./controllers/CreateDecryptController");
const router = (0, express_1.Router)();
exports.router = router;
const createEncryptController = new CreateEncryptController_1.CreateEncryptController();
const createDecryptController = new CreateDecryptController_1.CreateDecryptController();
router.post('/encript', createEncryptController.encrypt);
router.get('/encript/:id', createDecryptController.decrypt);
